stages:
  - build
  - pages
build-job: 
  stage: build
  tags: [linux, docker, x86-64]
  before_script: |

    rm -rf /etc/apt/sources.list
    mkdir -vp ${CARGO_HOME:-$HOME/.cargo}

    cat << EOF | tee -a /etc/apt/sources.list
      deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye main contrib non-free
      deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-updates main contrib non-free
    EOF
    cat << EOF | tee -a ${CARGO_HOME:-$HOME/.cargo}/config.toml
      [source.crates-io]
      replace-with = 'mirror'
      [source.mirror]
      registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"
    EOF

  script:
    - echo "build job start"
    - pwd
    - ls -l
    - apt-get update   
    - apt install -y cargo rustc
    - cargo install mdbook
    - mdbook build
    - ls -l book
    - echo "build ok"
  artifacts:
    paths:
      - "book"
    untracked: false
    when: on_success
    access: all
    expire_in: 30 days

pages:
  stage: pages
  needs:
    - build-job
  script:
    - echo "pages start"
    - mv book/* public/*
    - echo "pages ok"
  artifacts:
    paths:
      - "public"
    untracked: false
    when: on_success
    access: all
    expire_in: 30 days