name: Build and Publish
run-name: Build and Publish book (${{ gitea.actor }})
on: [push]

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: echo "OS=${{ runner.os }} NAME=${{ gitea.event_name }} REPO=${{ gitea.repository }} BRANCH=${{ gitea.ref }} ST=${{ job.status }} RUNID=${{ gitea.run_id }}"
      - name: Prepare Source
        run: |
          echo "--- write source ---"
          echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye main contrib non-free">/etc/apt/sources.list
          echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-updates main contrib non-free">>/etc/apt/sources.list
          echo "deb http://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-backports main contrib non-free">>/etc/apt/sources.list
          cat /etc/apt/sources.list
          rm -rf /etc/apt/sources.list.d/*
          echo "--- update source ---"
          apt-get update
      - name: Prepare Lftp
        run: |
          apt-get install lftp -y
      - name: Checkout
        uses: https://git.hmtsai.cn/actions/checkout@v4
      - name: Cache mdbook
        uses: https://git.hmtsai.cn/actions/cache@v4
        id: cache-mdbook
        env:
          cache-name: cache-mdbook
        with:
          key: ${{ runner.os }}-mdbook
          path: |
            study-area-action-deps
      - name: Get file
        if: ${{ steps.cache-mdbook.outputs.cache-hit != 'true' }}
        run: |
          git clone https://git.hmtsai.cn/cxykevin/study-area-action-deps
          echo "Check..."
          ls study-area-action-deps
      - name: Add permission
        run: chmod +x study-area-action-deps/mdbook-linux-$(uname -m)
      - name: Build mdbook
        run: study-area-action-deps/mdbook-linux-$(uname -m) build
      - name: Check book
        run: ls book
      - name: Upload
        run: lftp ${{ secrets.FTP_SITE }} -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PWD }} -e "mirror -R -P book index"

